name: Integration Tests

on:
  push:
    branches: [main, develop]
    paths:
      - "api/**"
      - "frontend/**"
      - "docker-compose.yml"
      - ".github/workflows/integration.yml"
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build with docker-compose
        run: docker-compose build

      - name: Start services
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: |
          # Wait for API to be healthy
          attempt=0
          max_attempts=10
          until docker-compose exec -T api curl -f http://localhost:8080/health || [ $attempt -eq $max_attempts ]
          do
            attempt=$((attempt+1))
            echo "Waiting for API to be ready... (attempt $attempt/$max_attempts)"
            sleep 5
          done

          if [ $attempt -eq $max_attempts ]; then
            echo "API failed to become healthy in time"
            docker-compose logs api
            exit 1
          fi

          # Wait for frontend to be ready
          attempt=0
          max_attempts=10
          until docker-compose exec -T frontend curl -f http://localhost:8080 || [ $attempt -eq $max_attempts ]
          do
            attempt=$((attempt+1))
            echo "Waiting for Frontend to be ready... (attempt $attempt/$max_attempts)"
            sleep 5
          done

          if [ $attempt -eq $max_attempts ]; then
            echo "Frontend failed to become healthy in time"
            docker-compose logs frontend
            exit 1
          fi

      - name: Run API smoke test
        run: |
          # Create a loan via API
          response=$(curl -s -X POST -H "Content-Type: application/json" \
            -d '{"borrowerName":"IntegrationTest","fundingAmount":1000,"repaymentAmount":1100}' \
            http://localhost:9090/api/loans)
          echo "API response: $response"

          # Extract loan ID from response for verification
          loan_id=$(echo $response | grep -o '"loanId":"[^"]*"' | cut -d'"' -f4)

          # Verify loan was created by getting it
          if curl -s http://localhost:9090/api/loans/$loan_id | grep -q "IntegrationTest"; then
            echo "✅ API test passed: Loan created and retrieved successfully"
          else
            echo "❌ API test failed: Could not verify loan creation"
            exit 1
          fi

      - name: Run Frontend smoke test
        run: |
          # Simple test to verify frontend is serving content correctly
          if curl -s http://localhost:80 | grep -q "Loan Management"; then
            echo "✅ Frontend test passed: Main page loaded with expected content"
          else
            echo "❌ Frontend test failed: Could not verify frontend content"
            curl -v http://localhost:80
            exit 1
          fi

      - name: Dump container logs on failure
        if: failure()
        run: |
          docker-compose logs

      - name: Stop services
        run: docker-compose down
