
services:
  # Backend API service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    container_name: loan-management-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # Frontend Angular application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    container_name: loan-management-frontend
    depends_on:
      - api
    restart: unless-stopped

networks:
  default:
    name: loan-management-network