# Default values for the Loan Management application
global:
  environment: production

# ServiceAccount configuration
serviceAccount:
  create: false
  annotations: {}
  name: ""

api:
  name: loan-management-api
  replicaCount: 1
  image:
    repository: "public.ecr.aws/o7k2q9z1/loan-management-api"
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  livenessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

frontend:
  name: loan-management-frontend
  replicaCount: 1
  image:
    repository: "public.ecr.aws/o7k2q9z1/loan-management-frontend"
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    - name: API_URL
      value: "/api"

ingress:
  enabled: true
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    # Set health check configuration per target group
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP

    # Health check for API endpoints (/api*)
    alb.ingress.kubernetes.io/conditions.api-group: '[{"field":"path-pattern","pathPatternConfig":{"values":["/api*"]}}]'
    alb.ingress.kubernetes.io/healthcheck-path.api-group: "/health"

    # Health check for frontend (everything else)
    alb.ingress.kubernetes.io/conditions.frontend-group: '[{"field":"path-pattern","pathPatternConfig":{"values":["/*"]}}]'
    alb.ingress.kubernetes.io/healthcheck-path.frontend-group: "/"

    # Global health check settings
    alb.ingress.kubernetes.io/success-codes: "200-399"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"

  hosts:
    - host: "" # Leave empty for the default host
      paths:
        - path: /
          pathType: Prefix
          serviceName: loan-management-frontend
          servicePort: 80
        - path: /api
          pathType: Prefix
          serviceName: loan-management-api
          servicePort: 8080
