apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    {{- include "loan-management.frontend.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 8080;
      listen [::]:8080;
      
      server_name _;
      
      root /usr/share/nginx/html;
      index index.html;
      
      location / {
        try_files $uri $uri/ /index.html;
      }
      
      location /api/ {
        proxy_pass http://{{ .Values.api.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.api.service.port }}/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }