name: Loan Management API CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - "api/**"
      - ".github/workflows/api.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "api/**"
      - ".github/workflows/api.yml"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Build Docker image
        run: docker build -t loan-management-api:${{ github.sha }} .

      - name: Export Docker image
        if: github.ref == 'refs/heads/main'
        run: docker save loan-management-api:${{ github.sha }} > loan-management-api.tar

      - name: Upload Docker image as artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: loan-management-api-image
          path: ./api/loan-management-api.tar
          retention-days: 1
