name: Loan Management System CI/CD

on:
  push:
    branches: [ '**' ]  # Run on push to any branch
  workflow_dispatch:    # Allow manual triggering

jobs:
  # API Tests
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

  # Frontend Tests
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test -- --watch=false --browsers=ChromeHeadless

  # API Build
  build-api:
    needs: [test-api]
    if: ${{ success() && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build API Docker image
      run: docker build -t loan-management-api:${{ github.sha }} .
    
    # Example for pushing to a registry (commented out)
    # - name: Login to container registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: your-registry.example.com
    #     username: ${{ secrets.REGISTRY_USERNAME }}
    #     password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # - name: Push API image
    #   run: |
    #     docker tag loan-management-api:${{ github.sha }} your-registry.example.com/loan-management-api:${{ github.sha }}
    #     docker tag loan-management-api:${{ github.sha }} your-registry.example.com/loan-management-api:latest
    #     docker push your-registry.example.com/loan-management-api:${{ github.sha }}
    #     docker push your-registry.example.com/loan-management-api:latest

  # Frontend Build
  build-frontend:
    needs: [test-frontend]
    if: ${{ success() && (github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Frontend Docker image
      run: docker build -t loan-management-frontend:${{ github.sha }} .
    
    # Example for pushing to a registry (commented out)
    # - name: Login to container registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: your-registry.example.com
    #     username: ${{ secrets.REGISTRY_USERNAME }}
    #     password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # - name: Push Frontend image
    #   run: |
    #     docker tag loan-management-frontend:${{ github.sha }} your-registry.example.com/loan-management-frontend:${{ github.sha }}
    #     docker tag loan-management-frontend:${{ github.sha }} your-registry.example.com/loan-management-frontend:latest
    #     docker push your-registry.example.com/loan-management-frontend:${{ github.sha }}
    #     docker push your-registry.example.com/loan-management-frontend:latest